#!/usr/bin/env python3
"""Train a trainable, routed KV *memory* on top of the pretrained 40M HA model.

Proof of concept
----------------
The pretrained dense checkpoint (``speed_run_dense_muon_final.pt``) is loaded into
:class:`HAMemoryLM`.  A fixed pool of KV-cache chunks ("topic memory", 128 topics
x ``--chunks-per-topic`` chunks x 64 tokens, default ~16K) is initialised from the
skill text generated by ``generate_skill_kv_chunks_v1.py`` and kept resident in VRAM.
Each topic's tokens are *copied* into its chunks: the copies start identical but sit
at different positions and accumulate their own gradients, so every topic gets more
trainable memory capacity.

During training every text sequence is placed *after* the memory (positions are
shifted by the memory length).  Hierarchical routing selects, per query chunk,
only the few memory chunks relevant to the current topic, so the loss gradient
reaches just those chunks — a sparse, MoE-like update of the memory.  The memory
tensors are leaf parameters with no history back to the embeddings: gradients
change the KV memory but propagate no further.

The model weights are trainable only for the first ``--weight-train-tokens``
tokens (default 50M, lr ``--weight-lr`` = 5e-5).  Beyond that budget the weights
are frozen and *only* the KV memory keeps training: tests show that, given more
tokens, the weights start exploiting the routing to peek at the next token
(breaking causality), so the early budget adapts the weights to the memory while
staying causal, after which the memory alone continues to learn.

Validation compares, on the same held-out tokens, the loss of:

  * ORIGINAL: the dense checkpoint (memory disabled), and
  * MEMORY:   the same weights with the routed KV memory attached.

Usage
-----
    python -m ExistingModelFineTuning.TestModel40M.KV_Memory.train_kv_memory \
        --steps 2000 --val-tokens 500000

    # quick smoke test
    python ExistingModelFineTuning/TestModel40M/KV_Memory/train_kv_memory.py \
        --smoke
"""

from __future__ import annotations

import argparse
import contextlib
import os
import sys
import time
from typing import List, Optional, Tuple

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, IterableDataset

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TESTMODEL_DIR = os.path.dirname(SCRIPT_DIR)
FINETUNE_DIR = os.path.dirname(TESTMODEL_DIR)
ROOT_DIR = os.path.dirname(FINETUNE_DIR)
for _p in (SCRIPT_DIR, ROOT_DIR):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from ha_memory_model import build_model, HAMemoryLM  # noqa: E402

DENSE_CHECKPOINT = os.path.join(FINETUNE_DIR, "speed_run_dense_muon_final.pt")
SKILL_DIR = os.path.join(SCRIPT_DIR, "skill_memory_gpt2")
DATA_DIR = os.path.join(ROOT_DIR, "fineweb_sample")
OUT_CHECKPOINT = os.path.join(SCRIPT_DIR, "ha_kv_memory.pt")

CHUNK_SIZE = 64


# -----------------------------------------------------------------------------
# Skill / memory tokens
# -----------------------------------------------------------------------------
def ensure_skill_tokens(skill_dir: str, tokenizer_name: str,
                        chunks_per_topic: int = 1) -> torch.Tensor:
    """Generate (if needed) and load the skill memory token ids as a flat tensor.

    ``chunks_per_topic`` duplicates each topic's 64-token chunk that many times
    (consecutively), so every topic gets ``chunks_per_topic`` KV-memory chunks seeded
    from the same tokens.  The copies start identical but live at different positions
    and attract their own gradients, giving each topic more trainable capacity.
    """
    pt_path = os.path.join(skill_dir, "skill_memory_input_ids.pt")
    if not os.path.exists(pt_path):
        print(f"Generating skill memory chunks with tokenizer '{tokenizer_name}' ...")
        from generate_skill_kv_chunks_v1 import build_chunks
        from pathlib import Path
        build_chunks(
            tokenizer_name=tokenizer_name,
            tokens_per_topic=CHUNK_SIZE,
            output_dir=Path(skill_dir),
            trust_remote_code=False,
        )
    tensor = torch.load(pt_path, map_location="cpu")  # [num_topics, tokens_per_topic]
    num_topics = tensor.shape[0]
    if chunks_per_topic > 1:
        tensor = tensor.repeat_interleave(chunks_per_topic, dim=0)
    flat = tensor.reshape(-1).long()
    print(f"Skill memory: {num_topics} topics x {chunks_per_topic} chunk(s)/topic x "
          f"{CHUNK_SIZE} tokens = {flat.numel()} tokens ({flat.numel() // CHUNK_SIZE} chunks)")
    return flat


# -----------------------------------------------------------------------------
# Data
# -----------------------------------------------------------------------------
class FineWebIterable(IterableDataset):
    """Pack fineweb documents into contiguous (input, target) windows."""

    def __init__(self, tokenizer, seq_len: int, parquet_files: List[str], skip_windows: int = 0):
        self.tokenizer = tokenizer
        self.seq_len = seq_len
        self.parquet_files = parquet_files
        self.skip_windows = skip_windows

    def __iter__(self):
        from datasets import load_dataset
        dataset = load_dataset(
            "parquet", data_files={"train": self.parquet_files}, streaming=True,
        )["train"]
        buf: List[int] = []
        produced = 0
        for example in dataset:
            tokens = self.tokenizer(example["text"], add_special_tokens=False)["input_ids"]
            if len(tokens) < 128:
                continue
            buf += tokens
            while len(buf) > self.seq_len:
                chunk = buf[: self.seq_len + 1]
                buf = buf[self.seq_len + 1:]
                produced += 1
                if produced <= self.skip_windows:
                    continue
                yield (torch.tensor(chunk[:-1], dtype=torch.long),
                       torch.tensor(chunk[1:], dtype=torch.long))
            if len(buf) < 128:
                buf = []


def get_data_files(data_dir: str, n_files: int = 2) -> List[str]:
    os.makedirs(data_dir, exist_ok=True)
    files = []
    for i in range(n_files):
        filename = f"sample/10BT/{i:03d}_00000.parquet"
        local_path = os.path.join(data_dir, filename)
        if not os.path.exists(local_path):
            from huggingface_hub import hf_hub_download
            print(f"  Downloading {filename} ...")
            hf_hub_download(
                repo_id="HuggingFaceFW/fineweb", filename=filename,
                repo_type="dataset", local_dir=data_dir,
            )
        files.append(local_path)
    return files


# -----------------------------------------------------------------------------
# Checkpoint
# -----------------------------------------------------------------------------
def load_dense_checkpoint(model: HAMemoryLM, path: str) -> None:
    payload = torch.load(path, map_location="cpu", weights_only=False)
    state = payload["model"] if isinstance(payload, dict) and "model" in payload else payload
    state = {k.replace("_orig_mod.", ""): v for k, v in state.items()}
    result = model.load_state_dict(state, strict=False)
    missing = [k for k in result.missing_keys if not k.startswith(("memory_k", "memory_v"))]
    if missing:
        raise RuntimeError(f"Unexpected missing keys when loading dense checkpoint: {missing}")
    if result.unexpected_keys:
        raise RuntimeError(f"Unexpected keys in dense checkpoint: {result.unexpected_keys}")
    print(f"Loaded dense checkpoint: {path}")


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------
@torch.no_grad()
def evaluate(model: HAMemoryLM, tokenizer, parquet_files: List[str], seq_len: int,
             target_tokens: int, device: str, use_memory: bool,
             amp_dtype: Optional[torch.dtype]) -> Tuple[float, int]:
    """Mean token cross-entropy over ~``target_tokens`` held-out tokens."""
    was_training = model.training
    model.eval()
    ds = FineWebIterable(tokenizer, seq_len, parquet_files)
    loader = DataLoader(ds, batch_size=1, num_workers=0)

    total_loss = 0.0
    total_tokens = 0
    for inputs, targets in loader:
        inputs = inputs.to(device).long()
        targets = targets.to(device).long()
        ctx = (torch.amp.autocast(device_type="cuda", dtype=amp_dtype)
               if (amp_dtype is not None and device == "cuda") else contextlib.nullcontext())
        with ctx:
            logits, _ = model(inputs, use_memory=use_memory)
        loss = F.cross_entropy(logits.reshape(-1, logits.shape[-1]).float(),
                               targets.reshape(-1), reduction="sum")
        n = targets.numel()
        total_loss += float(loss.item())
        total_tokens += n
        if total_tokens >= target_tokens:
            break

    model.train(was_training)
    return total_loss / max(total_tokens, 1), total_tokens


def report_validation(model, tokenizer, val_files, seq_len, val_tokens, device, amp_dtype, tag=""):
    print("-" * 64)
    orig_loss, n0 = evaluate(model, tokenizer, val_files, seq_len, val_tokens, device,
                             use_memory=False, amp_dtype=amp_dtype)
    mem_loss, n1 = evaluate(model, tokenizer, val_files, seq_len, val_tokens, device,
                            use_memory=True, amp_dtype=amp_dtype)
    import math
    print(f"VALIDATION {tag}")
    print(f"  ORIGINAL (no memory) : loss={orig_loss:.4f}  ppl={math.exp(orig_loss):.3f}  tokens={n0}")
    print(f"  MEMORY   (KV memory) : loss={mem_loss:.4f}  ppl={math.exp(mem_loss):.3f}  tokens={n1}")
    print(f"  delta loss (memory - original) = {mem_loss - orig_loss:+.4f}")
    print("-" * 64)
    return orig_loss, mem_loss


@torch.no_grad()
def report_causality(model, tokenizer, val_files, device, amp_dtype,
                     causality_seq: int, use_memory: bool = True):
    """Causality check: a ``causality_seq``-token window scored as prefill vs token-by-token.

    The decode pass feeds the *ground-truth* prefix tokens one at a time (no generated
    tokens are fed back), so prefill and decode see identical inputs.  If the routed
    attention is causal the two teacher-forced losses match; a large gap means a query
    is leaking information from future tokens through the routing.
    """
    ds = FineWebIterable(tokenizer, causality_seq, val_files)
    loader = DataLoader(ds, batch_size=1, num_workers=0)
    try:
        inputs, _ = next(iter(loader))
    except StopIteration:
        print("CAUSALITY: no validation window available")
        return None
    inputs = inputs.to(device).long()
    ctx = (torch.amp.autocast(device_type="cuda", dtype=amp_dtype)
           if (amp_dtype is not None and device == "cuda") else contextlib.nullcontext())
    with ctx:
        rep = model.validate_causality(inputs, use_memory=use_memory)
    print(f"CAUSALITY ({inputs.shape[1]} tok, decode vs prefill): "
          f"prefill={rep['prefill_loss']:.4f}  decode={rep['decode_loss']:.4f}  "
          f"delta={rep['delta']:+.4f}  max|dlogit|={rep['max_logit_diff']:.3e}")
    print("-" * 64)
    return rep


# -----------------------------------------------------------------------------
# Training
# -----------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dense-checkpoint", default=DENSE_CHECKPOINT)
    parser.add_argument("--skill-dir", default=SKILL_DIR)
    parser.add_argument("--data-dir", default=DATA_DIR)
    parser.add_argument("--out", default=OUT_CHECKPOINT)
    parser.add_argument("--tokenizer", default="gpt2")
    parser.add_argument("--seq-len", type=int, default=7*1024)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--accum-steps", type=int, default=7,
                        help="Gradient-accumulation micro-steps per optimizer update "
                             "(effective batch = batch_size * seq_len * accum_steps ~= 48K).")
    parser.add_argument("--topk-chunks", type=int, default=20)
    parser.add_argument("--chunks-per-topic", type=int, default=2,
                        help="KV-memory chunks per topic; each topic's tokens are copied into "
                             "every chunk (128 topics x 64 tok x this; default 2 -> ~16K memory).")
    parser.add_argument("--causality-seq", type=int, default=512,
                        help="Sequence length for the prefill-vs-decode causality check.")
    parser.add_argument("--steps", type=int, default=8000)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight-lr", type=float, default=3e-5,
                        help="LR for the (pretrained) model weights.")
    parser.add_argument("--weight-train-tokens", type=int, default=50_000_000,
                        help="Train model weights only for this many tokens, then freeze "
                             "them and train the KV memory alone (preserves causality).")
    parser.add_argument("--val-tokens", type=int, default=500_000)
    parser.add_argument("--val-every", type=int, default=500)
    parser.add_argument("--grad-clip", type=float, default=1.0)
    parser.add_argument("--freeze-weights", action="store_true",
                        help="Train only the KV memory; keep model weights frozen.")
    parser.add_argument("--n-data-files", type=int, default=2)
    parser.add_argument("--precision", choices=["bf16", "fp32"], default="bf16")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--smoke", action="store_true",
                        help="Tiny end-to-end run (few steps, small val budget).")
    args = parser.parse_args()

    if args.smoke:
        args.steps = 5
        args.val_tokens = 8192
        args.val_every = 5
        args.seq_len = 256
        args.batch_size = 1
        args.weight_train_tokens = 512  # exercise the freeze path within a few steps
        args.accum_steps = 2
        args.chunks_per_topic = 1  # keep smoke memory small/fast
        args.causality_seq = 128

    device = args.device
    amp_dtype = torch.bfloat16 if (args.precision == "bf16" and device == "cuda"
                                   and torch.cuda.is_bf16_supported()) else None

    from transformers import GPT2TokenizerFast
    tokenizer = GPT2TokenizerFast.from_pretrained(args.tokenizer)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    vocab_size = len(tokenizer)

    assert args.seq_len % CHUNK_SIZE == 0, "seq_len must be a multiple of chunk_size (64)"

    # --- model + dense weights
    model = build_model(vocab_size, ignore_index=-100, chunk_size=CHUNK_SIZE,
                        topk_chunks=args.topk_chunks).to(device)
    load_dense_checkpoint(model, args.dense_checkpoint)
    print(f"Model parameters (weights): {model.count_parameters():,}")

    # --- KV memory init from skill tokens
    skill_tokens = ensure_skill_tokens(args.skill_dir, args.tokenizer, args.chunks_per_topic)
    print(f"init_memory_from_tokens...")
    model.init_memory_from_tokens(skill_tokens)
    print(f"init_memory_from_tokens done")
    model.to(device)
    #model = torch.compile(model)

    n_mem = sum(p.numel() for p in model.memory_parameters())
    print(f"KV memory parameters: {n_mem:,} "
          f"({len(model.memory_k)} layers x {model.memory_k[0].shape})")

    # --- data: dedicate the first parquet file to validation, the rest to
    # training, so the held-out comparison never overlaps the training stream.
    data_files = get_data_files(args.data_dir, n_files=args.n_data_files)
    if len(data_files) > 1:
        val_files, train_files = data_files[:1], data_files[1:]
    else:
        val_files, train_files = data_files, data_files
        print("WARNING: only one data file available; validation overlaps training.")

    # --- baseline validation (before any training)
    #report_validation(model, tokenizer, val_files, args.seq_len, args.val_tokens,
    #                  device, amp_dtype, tag="(step 0, before training)")
    #report_causality(model, tokenizer, val_files, device, amp_dtype, args.causality_seq)

    # --- optimizer: memory always trained; weights optional
    model.train()
    mem_params = model.memory_parameters()
    mem_ids = {id(p) for p in mem_params}
    weight_params = [p for p in model.parameters() if id(p) not in mem_ids]
    if args.freeze_weights:
        for p in weight_params:
            p.requires_grad_(False)
    param_groups = [{"params": mem_params, "lr": args.lr}]
    if not args.freeze_weights:
        param_groups.append({"params": weight_params, "lr": args.weight_lr})
        print(f"Model weights trainable (lr={args.weight_lr:g}) for the first "
              f"{args.weight_train_tokens:,} tokens, then KV memory only.")
    optimizer = torch.optim.AdamW(param_groups, betas=(0.9, 0.95), eps=1e-8, weight_decay=0.0)
    eff_batch = args.batch_size * args.seq_len * args.accum_steps
    print(f"Effective batch: {args.batch_size} x {args.seq_len} tok x {args.accum_steps} accum "
          f"= {eff_batch:,} tokens / optimizer update")

    # --- train loop
    train_ds = FineWebIterable(tokenizer, args.seq_len, train_files)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, num_workers=0)
    data_iter = iter(train_loader)

    start = time.time()
    tokens_seen = 0
    weights_frozen = args.freeze_weights
    gn = 0.0
    optimizer.zero_grad(set_to_none=True)
    for step in range(1, args.steps + 1):
        try:
            inputs, targets = next(data_iter)
        except StopIteration:
            data_iter = iter(train_loader)
            inputs, targets = next(data_iter)
        inputs = inputs.to(device).long()
        targets = targets.to(device).long()

        ctx = (torch.amp.autocast(device_type="cuda", dtype=amp_dtype)
               if amp_dtype is not None else contextlib.nullcontext())
        with ctx:
            _, loss = model(inputs, labels=targets, use_memory=True)

        # Gradient accumulation: scale so accumulated grads average the micro-batches,
        # then update once every ``accum_steps`` (effective batch ~= 48K tokens).
        (loss / args.accum_steps).backward()
        if step % args.accum_steps == 0:
            gn = torch.nn.utils.clip_grad_norm_(
                [p for p in model.parameters() if p.requires_grad], args.grad_clip)
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

        # Freeze the model weights once the weight-training token budget is spent;
        # from here only the KV memory keeps learning (preserves causality).
        tokens_seen += inputs.numel()
        if not weights_frozen and tokens_seen >= args.weight_train_tokens:
            for p in weight_params:
                p.requires_grad_(False)
            weights_frozen = True
            print(f">>> {tokens_seen:,} tokens reached - freezing model weights; "
                  f"training KV memory only from here.")

        if step % 10 == 0 or step == 1:
            tps = step * args.batch_size * args.seq_len / max(time.time() - start, 1e-9)
            mode = "mem-only" if weights_frozen else "weights+mem"
            print(f"step {step:5d} | loss {float(loss.item()):.4f} | "
                  f"grad {float(gn):.2f} | {tps:.0f} tok/s | {mode}")

        if args.val_every > 0 and step % args.val_every == 0:
            report_validation(model, tokenizer, val_files, args.seq_len, args.val_tokens,
                              device, amp_dtype, tag=f"(step {step})")
            report_causality(model, tokenizer, val_files, device, amp_dtype, args.causality_seq)

    # --- flush any remaining accumulated gradients
    if args.steps % args.accum_steps != 0:
        torch.nn.utils.clip_grad_norm_(
            [p for p in model.parameters() if p.requires_grad], args.grad_clip)
        optimizer.step()
        optimizer.zero_grad(set_to_none=True)

    # --- final validation + save
    report_validation(model, tokenizer, val_files, args.seq_len, args.val_tokens,
                      device, amp_dtype, tag="(final)")
    report_causality(model, tokenizer, val_files, device, amp_dtype, args.causality_seq)
    torch.save({
        "model": model.state_dict(),
        "memory_shape": tuple(model.memory_k[0].shape),
        "config": {"chunk_size": CHUNK_SIZE, "topk_chunks": args.topk_chunks,
                   "seq_len": args.seq_len, "weight_lr": args.weight_lr,
                   "weight_train_tokens": args.weight_train_tokens,
                   "chunks_per_topic": args.chunks_per_topic},
    }, args.out)
    print(f"Saved KV-memory model to {args.out}")


if __name__ == "__main__":
    main()
